heat_template_version: 2016-10-14
description: A load-balancer server
parameters:
  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: 2048-10-1-1
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: xenial-server-cloudimg-amd64-disk1
  key_name:
    type: string
    description: An ssh keypair name used for accessing the server.
    default: myk
  subnet_id:
    type: string
    description: Subnet used by the server
    default : 4ba321db-9247-454b-9274-faad8ec76461
  net_id:
    type: string
    description: Network ID to use for the instance.
    default: 9ec556ab-d458-470e-96bc-1bab0ef66fb9



resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks: [{ network: { get_param: net_id }}]
      admin_pass: pass
      user_data_format: RAW
      user_data: |
            #!/bin/bash
            sudo apt-get update
            sudo apt-get install -y python	
            wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py 
            python server.py 

  member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address: {get_attr: [server, first_address]}
      pool: { get_resource: pool }
      protocol_port: 8080
      subnet: {get_param: subnet_id}


